### ISSUE TITLE
Making editconf's -d flag optional

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb_gromacs#1]
Hi!
I find myself needing the `-box` option on `editconf`*, but given that the `-d` flag is not optional, my `-box` dimensions get overwritten by it, even if I set `-d` to `0` or a negative value.

So, would it be possible to remove the default value [here](https://github.com/bioexcel/biobb_gromacs/blob/63df5d3e79449bffe2b71defd5bf274d9e413eef/biobb_gromacs/gromacs/editconf.py#L71), and instead of adding it eagerly [here](https://github.com/bioexcel/biobb_gromacs/blob/63df5d3e79449bffe2b71defd5bf274d9e413eef/biobb_gromacs/gromacs/editconf.py#L102) just add something like:

```
if self.distance_to_molecule:
            self.cmd.append("-d " + str(self.distance_to_molecule))
            fu.log("Distance of the box to molecule: %6.2f" % self.distance_to_molecule, self.out_log, self.global_log)
```

I know this would leave the door open for someone not specifying neither `-d` nor `-box`, which shouldn't be allowed, right? So, perhaps what I'm asking for is to add the `-box` option and make it so either one of them is set.

IDK, let me know if this makes sense, I have no problem doing this myself, it should be fairly quick.

Cheers!

*: which I'll be able to use in the next release through the new [dev option](https://github.com/bioexcel/biobb_md/issues/51) (thanks!)

**Comment by PauAndrio** [comment]
Hi!

You are totally correct, force in every case the -d option was a conceptual error. Please check if this fix (f575140752aae49d4302958ff54189f6f18208e1) solves your problem.

Regards,
Pau Andrio
