### ISSUE TITLE
gmx make_ndx string mask

### ISSUE THREAD

**Issue by gbayarri** [bioexcel/biobb_gromacs#2]
In biobb_gromacs.make_ndx, the string mask (e.g. _echo -e 'a D*\n0 & ! 19\nname 20 FREEZE\nq'_) is not properly read. 

Testing the same tutorial in version 3.6 / 3.7 (with biobb_md instead of biobb_gromacs) runs properly.

Can be something related with the new biobb_common?

**Comment by adamhospital** [comment]
Solved changing the "echo" by an stdin file:

https://github.com/bioexcel/biobb_gromacs/blob/682220e87ba7c9e9c009328ea9e5f9f6c768a2a5/biobb_gromacs/gromacs/make_ndx.py#LL111C1-L113C69
