### ISSUE TITLE
In gmx_image the "output_selection" property is ignored if "center" is False 

### ISSUE THREAD

**Issue by PabloNA97** [bioexcel/biobb_gromacs#20]
If "center" property is set to False, the "center_selection" property (by default "System") seems to be used anyway. As a consequence, "output_selection" is completely ignored and "center_selection" is used to determine which atoms should be dumped in the output trajectory. I guess this is because the groups are written in the following order in the .stdin: "center_selection" "output_selection". And if no centering is requested just one group is required and just the first one is used. 

Maybe the easiest solution would be to avoid including the "center_selection" group in the .stdin whenever "center" is False. In that way the default value of "center_selection" would not mess with the output group.

 - OS: Ubuntu 
 - Python version: 3.10.0
 - BioBB version 4.0.0

**Comment by PauAndrio** [comment]
This issue has been moved to the biobb_analysis repo:
[biobb_analysis issue 22](https://github.com/bioexcel/biobb_analysis/issues/22)
