### ISSUE TITLE
grompp_mdrun is not creating "output_tpr_path" 

### ISSUE THREAD

**Issue by PabloNA97** [bioexcel/biobb_gromacs#4]
I think grompp_mdrun is using a temporal unique folder into which "internal.tpr" is written. Instead of creating the .tpr file in the corresponding step folder. Due to this, if one needs to image the trajectory afterwards with gmx_image, the .tpr file is not found in the corresponding step folder.

**Comment by PauAndrio** [comment]
I will recommend to use grompp and mdrun as different blocks. Anyway now if the output_tpr_path argument is used it will be written in the correct destination.
