### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Dan-Burns** [bioexcel/biobb_gromacs#5]
Hi,

I'm trying to conda install and I get the following error:
```
Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0

Your installed version is: 2.35
```
My os is Ubuntu 22.04.1

I've already got biobb_common installed.

Also, does this try to conda install gromacs?  Can I use my own existing install?

Thank you,
Dan

**Comment by PauAndrio** [comment]
Hi Dan,

That's a common anaconda error, that tends to appear when packages from anaconda-default and conda-forge channels 
are mixed. I recommend you create a new environment creating a `yaml` file with this content: 

```
name: biobbgromacs_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biobb_gromacs
```

You can edit the file change the env name and add all the extra dependencies that you need. The command to create it is (assuming your file is named biobbgromacs_env):
`conda env create --file biobbgromacs_env.yaml`


Answering your second question, yes, this will install the GROMACS 2022.2 version. However, you can use your own GROMACS installation using the `binary_path` property from the [documentation](https://biobb-gromacs.readthedocs.io/en/latest/gromacs.html#gromacs.mdrun.Mdrun): 
`binary_path (str) - (“gmx”) Path to the GROMACS executable binary.`

Regards,
Pau

**Comment by PauAndrio** [comment]
Hi Dan,

Try this environment file I think that i solves your problems except the biobb_ml one because of the weird dependencies of tensorflow:

```
name: custom_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - python==3.8

  # Biobb's
  - biobb_gromacs>=3.9.0
  - biobb_analysis>=3.9.0
  - biobb_model>=3.9.0
  - biobb_structure_utils>=3.9.0
  - biobb_amber>=3.9.0
  - biobb_cp2k>=3.9.0
  - biobb_cmip>=3.9.0
  # - biobb_ml>=3.9.0 tensorflow has lots of incompatibilities with python 3.10
  # - biobb_disgenet is not available at the moment

  # Jupyter Notebooks
  - jupyter::conda-forge
  - ipywidgets==7.6.6
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - plotly
  - nglview
  - simpletraj
  
  # Modeller
  - modeller::salilab

```
