### ISSUE TITLE
mdrun crashes with GPU settings on a machine with GPU

### ISSUE THREAD

**Issue by ndonyapour** [bioexcel/biobb_gromacs#6]
Hello,

I am trying to run MD using the `quay.io/biocontainers/biobb_md:3.7.2--pyhdfd78af_0` docker with GPU settings on a machine with 4 GPUS, but it crashes with the following error: 

```
Fatal error:
Cannot run short-ranged nonbonded interactions on a GPU because there is none detected.
```
I would be grateful for any insight you can provide.

Thank you,
Nazanin

**Comment by PauAndrio** [comment]
Sorry @ndonyapour, enable GPU usage in the biobb_gromacs docker is not a priority for our team right now.
