### ISSUE TITLE
mdrun wrapper trr optional

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_gromacs#8]
Make output_trr_path optional in mdrun. Nowadays trr is almost not used.

**Comment by PauAndrio** [comment]
Sorry, as far as I know there's no way to avoid Gromacs to create the TRR file.

Even if the user does not specify the output_trr_path which, right now, is not mandatory in the biobb_mdrun block. Gromacs is still going to create the trr file using a generic name.
